### ISSUE TITLE
Browse Action-Implementation in Shortcut Browser

### ISSUE THREAD

**Issue by BraunTom** [hpi-swa-teaching/Actions#31]
Define more actions like:
* browse method
* go to Class

**Comment by Tonybodo** [comment]
- Shortcut with default (Cmd + B ) to browse in Shortcut-Browser to action implementation

**Comment by Tonybodo** [comment]
As a user I would like to reach the implementation of the individual actions directly via a shortcut in order to view implementation quickly.

**Comment by Tonybodo** [comment]
Linked with #54
