### ISSUE TITLE
Help window/popup

### ISSUE THREAD

**Issue by ko-redtruck** [hpi-swa-teaching/Actions#32]
As a beginner level user I want to be able to open a help window which explains how to configure shortcuts in order to understand all functionalities and start using the tool efficiently.

Time: 5

Acceptance:

- seperate window or tooltip
- max 1 click away
- explain all fundamental functions
- understandable for new users

**Comment by ko-redtruck** [comment]
Unexpected behavior: you can edit the text inside the help window

**Comment by Tonybodo** [comment]
- Class instead of environment
- what happends after right klick
- you must have shortcuts when you remove
