### ISSUE TITLE
Default shortcuts

### ISSUE THREAD

**Issue by ko-redtruck** [hpi-swa-teaching/Actions#33]
As a User of the shortcuts I want a number of default shortcuts that are implemented immediately after installation, to lose no time for standard actions and to get started right away.

time: 5

Acceptance:
- shortcuts can be used directly after installation
- defualt implementation can easily be added to future shortcuts
- default imlementation can be seen in the shortcut browser (if default is strg+r for remove, entry in brwoser is remove(strg+r)

**Comment by Tonybodo** [comment]
Acceptance:

- you can override default implementations and the new combination triggers the action (old one no longer does)

**Comment by Franka-T** [comment]
As a user of the shortcuts I want to have a button to reset the configured shortcuts to the default shortcuts to be able to try out new action-key combinations, test how they work and reassemble them quickly.

time: 5

**Comment by Franka-T** [comment]
As a shortcut developer I want to be able to add default shortcuts in the ShortcutBrowser via an entry into a dictionary just passing the class, action and key combination to fit the default shortcuts to individual needs and preferences without having to add/change more than 1 line of code for each shortcut.

time: 5

**Comment by WilliamBrandt** [comment]
TODO:
alles in Actions mit zusatzfeld: wenn belegt ist das die default combination
Export Shortcuts
