### ISSUE TITLE
Reset to defaults

### ISSUE THREAD

**Issue by MatthisCl** [hpi-swa-teaching/Actions#38]
As a user i want to be able to reset my shortcuts to the default settings in order to quickly revert changes 
Acceptance:

- [x] button in configurator
- [x] popup with option to reset/canel
- [x] reset all shortcuts globally
- [x] reset shortcuts for a specific class 
- [x] remove my custom shortcuts for all actions

**Comment by ko-redtruck** [comment]
#42
