### ISSUE TITLE
Design Coding Standard

### ISSUE THREAD

**Issue by Tonybodo** [hpi-swa-teaching/Actions#67]
- [x] Commit messages
- [x] Branch naming
- [x] Issue naming
- [x] Issue formating and issue templates
- [x] Coding style and style guide
- [x] style linter for CI
- [x] test naming
- [x] workflow and process modeling

**Comment by MatthisCl** [comment]
Vorschläge:
Branch naming: type/issue_id_/description
type: bug, feature etc.

Commit messages: type [scope] description
type: fix, feat, test, ci, style, refactor, performance
scope: Main-Klasse die geändert wurde, optional

Issue naming: Short summary of user story

**Comment by Tonybodo** [comment]
Commit Message Style:
- blank line for separating body and subject
- no period behind subject
- capitalize subject and each paragraph
- only use more than 72
- in the body describe how and why you have done something, leave out details, but explain what the problem is what you tackle with the commit
- for subject use imperative and make clear what the commit is about

**Comment by Tonybodo** [comment]
Issue naming and conentions:
- I do not prefer a strict issue naming, the name from an issue should concisely describe what it is about
- every issue should either have a tag enhancement, bug or documentation
- every issue should have a state which fits to our workflow/working process
- every issue with enhancement label must have an annotated user story
- every issue should have an expected amount of time (rating) for his solution, issues with unknown rating have to tag with ? label

**Comment by Tonybodo** [comment]
Branches:
- Dev branch for main development, changes on the dev branch undergo reviews before merging with master
- QA branch which contains code for automation testing
- Masterbranch
- Working branches
--> for the transitions see workflow/process

**Comment by Tonybodo** [comment]
Branch naming
- we use hyphen to seperate word in branchname
- assign branch to one branch group like bug etc. und possible (See comment Matthis)
