### ISSUE TITLE
Global Actions

### ISSUE THREAD

**Issue by Tonybodo** [hpi-swa-teaching/Actions#88]
**Userstory**
As a user, I want to be able to define global actions, that can be added to all classes that support that action.  I want to have this feature in order to avoid defining the same action in multiple classes.

**Acceptance Criteria**
Blocked by #87
- [x] will be defined by #87 

**Reviewer**

**Comment by ko-redtruck** [comment]
Remove pragma from GlobalActions methods

**Comment by ko-redtruck** [comment]
Ignore global actions when reseting for only a selected class
